### ISSUE TITLE
using fsl bianca with LOCATE for MS lesion segmentation

### ISSUE THREAD

**Issue by dilekozkan** [neurolabusc/fsl_bianca#1]
I gave t1_brain as input to bianca. I mean image to derive non-zero (brain) mask from. this is not a binary/mask image - it has zeros outside the brain and non-zeros inside.
_How about for bianca LOCATE?_ Will I use this image or **just original registered T1 image for bianca LOCATE **? bianca locate says: Any other additional images that were used as _intensity features_ _in BIANCA._ **I used t1_brain as requested in bianca,** I did not use original raw t1.
Best,Dilek

**Comment by neurolabusc** [comment]
For usage of  LOCATE (LOCally Adaptive Thresholds Estimation) see the [FSL user guide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BIANCA/Userguide) or contact the [FSL jiscmail for support](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=fsl).
