### ISSUE TITLE
bianca LOCATE folder ingredients

### ISSUE THREAD

**Issue by dilekozkan** [neurolabusc/fsl_bianca#2]
My base image for registration is **DIR image**, because it is 3d image and it has more resolution. _But I am not using DIR image for classification._ As far as I understood it is not necessary at all. In this case do I have to create a file called like subj001_feature_DIR.nii.gz for it for the Locate folder?

Best,
Dilek

**Comment by neurolabusc** [comment]
The Matlab function A_getFLAIR.m uses the naming structure of the Aphasia Recovery Cohort, you will want to modify this for your own datasets.
